# Generated by Django 6.0.5 on 2026-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('artista', models.CharField(max_length=100, verbose_name='Artista')),
                ('album', models.CharField(blank=True, max_length=100, null=True, verbose_name='Álbum')),
                ('duracion', models.DurationField(help_text='Formato: MM:SS', verbose_name='Duración')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
