# Generated by Django 6.0.5 on 2026-06-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.CharField(blank=True, default='Single', max_length=100, null=True, verbose_name='Álbum'),
        ),
    ]
