# Generated by Django 6.0.5 on 2026-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_alter_cancion_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de YouTube'),
        ),
    ]
